### ISSUE TITLE
3000+ 分值题目样式丢失

### ISSUE THREAD

**Issue by huxulm** [huxulm/lc-rating#47]
可能由于迭代时没有注意导致。
原先:
<img src="https://github.com/user-attachments/assets/81864c21-7895-449d-a9f4-f5a4950d47dd" width="200"/>
现在:
<img src="https://github.com/user-attachments/assets/1f279a04-5485-48d3-b54b-b350b9541114" width="250"/>

![Image](https://github.com/user-attachments/assets/a776e0e7-a91d-437a-9da5-4ca512d0454b) @Autumnal-Joy 

<img src="https://github.com/user-attachments/assets/e3fcb3d4-9fab-4a78-b03f-eb71ab89e20e" height="30"/>

**Comment by Autumnal-Joy** [comment]
ok，我目前正在搞进度选项的问题，这个之后我看看

**Comment by Autumnal-Joy** [comment]
3000以上的题对应下标 idx=7 (这里的颜色c似乎定义了没用到)
```ts
// components/RatingCircle/index.tsx
export const COLORS = [
  { l: 0, r: 1200, c: "#ffffff" },
  { l: 1200, r: 1400, c: `#828282` },
  { l: 1400, r: 1600, c: `#4BA59E` },
  { l: 1600, r: 1900, c: `#1B01F5` },
  { l: 1900, r: 2100, c: `#9B1EA4` },
  { l: 2100, r: 2400, c: `#F09235` },
  { l: 2400, r: 3000, c: `#EA3323` },
  { l: 3000, r: 4000, c: `#EA3323` },
];
```

样式表里把idx=7设置为透明，所以边框变成透明了
```scss
// _common.scss
[data-bs-theme] {
  --rating-color-0: #848484;
  --rating-color-1: #595959;
  --rating-color-2: #4BA59E;
  --rating-color-3: #1B01F5;
  --rating-color-4: #9B1EA4;
  --rating-color-5: #F09235;
  --rating-color-6: #EA3323;
  --rating-color-7: transparent;
}
[data-bs-theme=dark] {
  color-scheme: dark;
  --rating-color-0: #c5c4c4;
  --rating-color-1: #ffffff;
  --rating-color-2: #74fff3;
  --rating-color-3: #6857ff;
  --rating-color-4: #ec60f6;
  --rating-color-5: #f8a95b;
  --rating-color-6: #f35041;
  --rating-color-7: transparent;
}
```

之前没出现问题是因为，添加了自定义属性 data="top"
```scss
// _common.scss
.inner-circle[data="top"] {
  border-color: var(--rating-color-6)!important;
}
```

字段命名不符合html规范，eslint报错，当时没注意到这个样式，被我当作bug修掉了 https://github.com/huxulm/lc-rating/pull/43#issuecomment-2673613378
